
# **Car Price Prediction::**


# **Problem Statement::**

A Chinese automobile company Geely Auto aspires to enter the US market by setting up their manufacturing unit there and producing cars locally to give competition to their US and European counterparts.

They have contracted an automobile consulting company to understand the factors on which the pricing of cars depends. Specifically, they want to understand the factors affecting the pricing of cars in the American market, since those may be very different from the Chinese market. The company wants to know:

Which variables are significant in predicting the price of a car How well those variables describe the price of a car Based on various market surveys, the consulting firm has gathered a large data set of different types of cars across the America market.

#**task::**

We are required to model the price of cars with the available independent variables. It will be used by the management to understand how exactly the prices vary with the independent variables. They can accordingly manipulate the design of the cars, the business strategy etc. to meet certain price levels. Further, the model will be a good way for management to understand the pricing dynamics of a new market.

#**WORKFLOW ::**
1.Load Data

2.Check Missing Values ( If Exist ; Fill each record with mean of its feature )

3.Split into 50% Training(Samples,Labels) , 30% Test(Samples,Labels) and 20% Validation Data(Samples,Labels).

4.Model : input Layer (No. of features ), 3 hidden layers including 10,8,6 unit & Output Layer with activation function relu/tanh (check by experiment).

5.Compilation Step (Note : Its a Regression problem , select loss , metrics according to it) 6.Train the Model with Epochs (100) and validate it

7.If the model gets overfit tune your model by changing the units , No. of layers , activation function , epochs , add dropout layer or add Regularizer according to the need .

8.Evaluation Step

9.Prediction

In [ ]:
import numpy as np
import pandas as pd
import tensorflow.keras as tf
from tensorflow.keras import models, layers, optimizers
import matplotlib.pyplot as plt

# 1.Load Data

In [ ]:
df = pd.read_csv("sample_data/CarPrice_Assignment.csv")
df

     car_ID  symboling                   CarName  ... citympg highwaympg    price
0         1          3        alfa-romero giulia  ...      21         27  13495.0
1         2          3       alfa-romero stelvio  ...      21         27  16500.0
2         3          1  alfa-romero Quadrifoglio  ...      19         26  16500.0
3         4          2               audi 100 ls  ...      24         30  13950.0
4         5          2                audi 100ls  ...      18         22  17450.0
..      ...        ...                       ...  ...     ...        ...      ...
200     201         -1           volvo 145e (sw)  ...      23         28  16845.0
201     202         -1               volvo 144ea  ...      19         25  19045.0
202     203         -1               volvo 244dl  ...      18         23  21485.0
203     204         -1                 volvo 246  ...      26         27  22470.0
204     205         -1               volvo 264gl  ...      19         25  22625.0

[205 rows x 26 columns]

# 2.Check Missing Values ( If Exist ; Fill each record with mean of its feature )

In [ ]:
df.isnull().sum()

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

NO missing value in dataset

In [ ]:
df.drop(columns=['car_ID'], inplace = True)
df

     symboling                   CarName fueltype  ... citympg highwaympg    price
0            3        alfa-romero giulia      gas  ...      21         27  13495.0
1            3       alfa-romero stelvio      gas  ...      21         27  16500.0
2            1  alfa-romero Quadrifoglio      gas  ...      19         26  16500.0
3            2               audi 100 ls      gas  ...      24         30  13950.0
4            2                audi 100ls      gas  ...      18         22  17450.0
..         ...                       ...      ...  ...     ...        ...      ...
200         -1           volvo 145e (sw)      gas  ...      23         28  16845.0
201         -1               volvo 144ea      gas  ...      19         25  19045.0
202         -1               volvo 244dl      gas  ...      18         23  21485.0
203         -1                 volvo 246   diesel  ...      26         27  22470.0
204         -1               volvo 264gl      gas  ...      19         25  22625.0

[205 rows x 25 columns]

In [ ]:
# one hot encoding for catagorical columns
final_df = pd.get_dummies(df, columns=['CarName','symboling','fueltype',	'aspiration',	'doornumber',	'carbody',	'drivewheel',	'enginelocation',	'enginetype',	'cylindernumber',	'fuelsystem'], drop_first = True)

In [ ]:
final_df

     wheelbase  carlength  ...  fuelsystem_spdi  fuelsystem_spfi
0         88.6      168.8  ...                0                0
1         88.6      168.8  ...                0                0
2         94.5      171.2  ...                0                0
3         99.8      176.6  ...                0                0
4         99.4      176.6  ...                0                0
..         ...        ...  ...              ...              ...
200      109.1      188.8  ...                0                0
201      109.1      188.8  ...                0                0
202      109.1      188.8  ...                0                0
203      109.1      188.8  ...                0                0
204      109.1      188.8  ...                0                0

[205 rows x 194 columns]

In [ ]:

#checking abnormal values and outliers
final_df.describe()

        wheelbase   carlength  ...  fuelsystem_spdi  fuelsystem_spfi
count  205.000000  205.000000  ...       205.000000       205.000000
mean    98.756585  174.049268  ...         0.043902         0.004878
std      6.021776   12.337289  ...         0.205380         0.069843
min     86.600000  141.100000  ...         0.000000         0.000000
25%     94.500000  166.300000  ...         0.000000         0.000000
50%     97.000000  173.200000  ...         0.000000         0.000000
75%    102.400000  183.100000  ...         0.000000         0.000000
max    120.900000  208.100000  ...         1.000000         1.000000

[8 rows x 194 columns]

# 3.Split into 50% Training(Samples,Labels) , 30% Test(Samples,Labels) and 20% Validation Data(Samples,Labels).

In [20]:

train_data, validate_data, test_data  = np.split(final_df.sample(frac=1, random_state=123), 
                       [int(.5*len(final_df)), int(.7*len(final_df))])

In [24]:
train_data.shape

(102, 194)

In [25]:
validate_data.shape

(41, 194)

In [27]:
test_data.shape

(62, 194)

In [28]:
train_label = train_data.loc[:,'price']
test_label = test_data.loc[:,'price']

In [29]:
test_data = test_data.drop(columns=['price'])
train_data = train_data.drop(columns=['price'])